### ISSUE TITLE
test script

### ISSUE THREAD

**Issue by cryax** [HKUST-KnowComp/DMSCMC#1]
Hi,
Is there any script that allow me to run test for a single raw text mention ?

**Comment by zwjyyc** [comment]
Hi, cryax

We haven't implemented a specific API for a single raw text.  If you are familiar with python, you can place your input in dev or test file, and directly modify the results which are numpy arrays (line 350 or 424 in DMSCMC.py).

Hope this helps you!

**Comment by cryax** [comment]
Hi, I tried to modify your code a little bit to load base model and input a raw text but I got different results for 1 mention.

**Comment by cryax** [comment]
Here's my test script with create_batches_test is the same as your create_batches without grouth_truth.
![image](https://user-images.githubusercontent.com/16573469/33806952-0f23a392-de02-11e7-8e33-cb335a07dd56.png)
main script:
![image](https://user-images.githubusercontent.com/16573469/33806983-87f8db5c-de02-11e7-8d02-871f68641832.png)
